### ISSUE TITLE
2.1.1 Blank.qtz not included

### ISSUE THREAD

**Issue by mikegoodspeed** [theseal/macos-blank-screensaver#6]
The changes for issue #3 do not include a `Blank.qtz` file. I think we need to include this file to update the cask in [theseal/homebrew-blank-screensaver](https://github.com/theseal/homebrew-blank-screensaver).

**Comment by mikegoodspeed** [comment]
I can build the Xcode project, which creates the `Blank.saver` but how do you convert it to the `Blank.qtz`?

**Comment by simmel** [comment]
I saw that when I built it.

But since `.qtz`-files aren't used anymore do we really need to update and build it?

**Comment by theseal** [comment]
Seems like you forgot the documentation in your PR (#5)  @simmel  😉 

`.qtz` does not to work in Big Sur as it did in all other releases of macOS/OSX (except Mojave).

`.saver` requires that you allow unsigned binaries since the one we provide is not signed. Maybe that should be included in the documentation as well.

I never signed something for macOS before, is it easy?

**Comment by mikegoodspeed** [comment]
I think we should figure out how to sign the `Blank.saver` but for now I have worked around this problem with `xattr -d com.apple.quarantine '~/Library/Screen Savers/Blank.saver'` and put that code in a PR [thesal/homebrew-blank-screensaver#4](https://github.com/theseal/homebrew-blank-screensaver/pull/4).
